// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA04z4GvzZE6SOyUnpuaZqE8BLQ7KL3ErM',
    appId: '1:63452043288:web:34a40006dd73b32cb74b6d',
    messagingSenderId: '63452043288',
    projectId: 'clinic-crm-bf690',
    authDomain: 'clinic-crm-bf690.firebaseapp.com',
    storageBucket: 'clinic-crm-bf690.firebasestorage.app',
    measurementId: 'G-KLG0FG0JXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC0LzwQOis3lw1oggl42GGwI5HONuGHfM',
    appId: '1:63452043288:android:0100e477ec2b4f9bb74b6d',
    messagingSenderId: '63452043288',
    projectId: 'clinic-crm-bf690',
    storageBucket: 'clinic-crm-bf690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkQA3KzqRMT8xdPmYc6Rz51BnEcDKRuHM',
    appId: '1:63452043288:ios:f82f5120a850758bb74b6d',
    messagingSenderId: '63452043288',
    projectId: 'clinic-crm-bf690',
    storageBucket: 'clinic-crm-bf690.firebasestorage.app',
    iosBundleId: 'com.example.raClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkQA3KzqRMT8xdPmYc6Rz51BnEcDKRuHM',
    appId: '1:63452043288:ios:f82f5120a850758bb74b6d',
    messagingSenderId: '63452043288',
    projectId: 'clinic-crm-bf690',
    storageBucket: 'clinic-crm-bf690.firebasestorage.app',
    iosBundleId: 'com.example.raClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA04z4GvzZE6SOyUnpuaZqE8BLQ7KL3ErM',
    appId: '1:63452043288:web:24dc0efdc5c84042b74b6d',
    messagingSenderId: '63452043288',
    projectId: 'clinic-crm-bf690',
    authDomain: 'clinic-crm-bf690.firebaseapp.com',
    storageBucket: 'clinic-crm-bf690.firebasestorage.app',
    measurementId: 'G-HY67NMFV1M',
  );
}
